// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pkg/nex.proto

package nex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InterfaceRequest) Reset() {
	*x = InterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceRequest) ProtoMessage() {}

func (x *InterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceRequest.ProtoReflect.Descriptor instead.
func (*InterfaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{0}
}

func (x *InterfaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InterfaceResponse) Reset() {
	*x = InterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceResponse) ProtoMessage() {}

func (x *InterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceResponse.ProtoReflect.Descriptor instead.
func (*InterfaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{1}
}

// network ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subnet4       string        `protobuf:"bytes,2,opt,name=subnet4,proto3" json:"subnet4,omitempty"`
	Subnet6       string        `protobuf:"bytes,3,opt,name=subnet6,proto3" json:"subnet6,omitempty"`
	Dhcp4Server   string        `protobuf:"bytes,4,opt,name=dhcp4server,proto3" json:"dhcp4server,omitempty"`
	Dhcp6Server   string        `protobuf:"bytes,5,opt,name=dhcp6server,proto3" json:"dhcp6server,omitempty"`
	Range4        *AddressRange `protobuf:"bytes,6,opt,name=range4,proto3" json:"range4,omitempty"`
	Range6        *AddressRange `protobuf:"bytes,7,opt,name=range6,proto3" json:"range6,omitempty"`
	Gateways      []string      `protobuf:"bytes,8,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Nameservers   []string      `protobuf:"bytes,9,rep,name=nameservers,proto3" json:"nameservers,omitempty"`
	Options       []*Option     `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Domain        string        `protobuf:"bytes,11,opt,name=domain,proto3" json:"domain,omitempty"`
	Excluded      []string      `protobuf:"bytes,12,rep,name=excluded,proto3" json:"excluded,omitempty"`
	Siaddr        string        `protobuf:"bytes,13,opt,name=siaddr,proto3" json:"siaddr,omitempty"`
	LeaseDuration uint64        `protobuf:"varint,14,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetSubnet4() string {
	if x != nil {
		return x.Subnet4
	}
	return ""
}

func (x *Network) GetSubnet6() string {
	if x != nil {
		return x.Subnet6
	}
	return ""
}

func (x *Network) GetDhcp4Server() string {
	if x != nil {
		return x.Dhcp4Server
	}
	return ""
}

func (x *Network) GetDhcp6Server() string {
	if x != nil {
		return x.Dhcp6Server
	}
	return ""
}

func (x *Network) GetRange4() *AddressRange {
	if x != nil {
		return x.Range4
	}
	return nil
}

func (x *Network) GetRange6() *AddressRange {
	if x != nil {
		return x.Range6
	}
	return nil
}

func (x *Network) GetGateways() []string {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *Network) GetNameservers() []string {
	if x != nil {
		return x.Nameservers
	}
	return nil
}

func (x *Network) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Network) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Network) GetExcluded() []string {
	if x != nil {
		return x.Excluded
	}
	return nil
}

func (x *Network) GetSiaddr() string {
	if x != nil {
		return x.Siaddr
	}
	return ""
}

func (x *Network) GetLeaseDuration() uint64 {
	if x != nil {
		return x.LeaseDuration
	}
	return 0
}

type NetworkUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subnet4            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=subnet4,proto3" json:"subnet4,omitempty"`
	Subnet6            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=subnet6,proto3" json:"subnet6,omitempty"`
	Dhcp4Server        *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=dhcp4server,proto3" json:"dhcp4server,omitempty"`
	Dhcp6Server        *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=dhcp6server,proto3" json:"dhcp6server,omitempty"`
	Range4             *AddressRange           `protobuf:"bytes,6,opt,name=Range4,proto3" json:"Range4,omitempty"`
	Range6             *AddressRange           `protobuf:"bytes,7,opt,name=Range6,proto3" json:"Range6,omitempty"`
	GatewaysPresent    []string                `protobuf:"bytes,8,rep,name=gateways_present,json=gatewaysPresent,proto3" json:"gateways_present,omitempty"`
	GatewaysAbsent     []string                `protobuf:"bytes,9,rep,name=gateways_absent,json=gatewaysAbsent,proto3" json:"gateways_absent,omitempty"`
	NameserversPresent []string                `protobuf:"bytes,10,rep,name=nameservers_present,json=nameserversPresent,proto3" json:"nameservers_present,omitempty"`
	NameserversAbsent  []string                `protobuf:"bytes,11,rep,name=nameservers_absent,json=nameserversAbsent,proto3" json:"nameservers_absent,omitempty"`
	OptionsPresent     []*Option               `protobuf:"bytes,12,rep,name=options_present,json=optionsPresent,proto3" json:"options_present,omitempty"`
	OptionsAbsent      []*Option               `protobuf:"bytes,13,rep,name=options_absent,json=optionsAbsent,proto3" json:"options_absent,omitempty"`
	Domain             *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=domain,proto3" json:"domain,omitempty"`
	MacRange           *AddressRange           `protobuf:"bytes,15,opt,name=macRange,proto3" json:"macRange,omitempty"`
	Siaddr             *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=siaddr,proto3" json:"siaddr,omitempty"`
	LeaseDuration      *wrapperspb.UInt64Value `protobuf:"bytes,17,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
}

func (x *NetworkUpdateRequest) Reset() {
	*x = NetworkUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUpdateRequest) ProtoMessage() {}

func (x *NetworkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUpdateRequest.ProtoReflect.Descriptor instead.
func (*NetworkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkUpdateRequest) GetSubnet4() *wrapperspb.StringValue {
	if x != nil {
		return x.Subnet4
	}
	return nil
}

func (x *NetworkUpdateRequest) GetSubnet6() *wrapperspb.StringValue {
	if x != nil {
		return x.Subnet6
	}
	return nil
}

func (x *NetworkUpdateRequest) GetDhcp4Server() *wrapperspb.StringValue {
	if x != nil {
		return x.Dhcp4Server
	}
	return nil
}

func (x *NetworkUpdateRequest) GetDhcp6Server() *wrapperspb.StringValue {
	if x != nil {
		return x.Dhcp6Server
	}
	return nil
}

func (x *NetworkUpdateRequest) GetRange4() *AddressRange {
	if x != nil {
		return x.Range4
	}
	return nil
}

func (x *NetworkUpdateRequest) GetRange6() *AddressRange {
	if x != nil {
		return x.Range6
	}
	return nil
}

func (x *NetworkUpdateRequest) GetGatewaysPresent() []string {
	if x != nil {
		return x.GatewaysPresent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetGatewaysAbsent() []string {
	if x != nil {
		return x.GatewaysAbsent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetNameserversPresent() []string {
	if x != nil {
		return x.NameserversPresent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetNameserversAbsent() []string {
	if x != nil {
		return x.NameserversAbsent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetOptionsPresent() []*Option {
	if x != nil {
		return x.OptionsPresent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetOptionsAbsent() []*Option {
	if x != nil {
		return x.OptionsAbsent
	}
	return nil
}

func (x *NetworkUpdateRequest) GetDomain() *wrapperspb.StringValue {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *NetworkUpdateRequest) GetMacRange() *AddressRange {
	if x != nil {
		return x.MacRange
	}
	return nil
}

func (x *NetworkUpdateRequest) GetSiaddr() *wrapperspb.StringValue {
	if x != nil {
		return x.Siaddr
	}
	return nil
}

func (x *NetworkUpdateRequest) GetLeaseDuration() *wrapperspb.UInt64Value {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

type NetworkUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NetworkUpdateResponse) Reset() {
	*x = NetworkUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkUpdateResponse) ProtoMessage() {}

func (x *NetworkUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkUpdateResponse.ProtoReflect.Descriptor instead.
func (*NetworkUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{4}
}

type AddressRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Begin string `protobuf:"bytes,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *AddressRange) Reset() {
	*x = AddressRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRange) ProtoMessage() {}

func (x *AddressRange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRange.ProtoReflect.Descriptor instead.
func (*AddressRange) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{5}
}

func (x *AddressRange) GetBegin() string {
	if x != nil {
		return x.Begin
	}
	return ""
}

func (x *AddressRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{6}
}

func (x *Option) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Option) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// memberhsip ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
type AddMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Mac     []string `protobuf:"bytes,2,rep,name=mac,proto3" json:"mac,omitempty"`
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{7}
}

func (x *AddMemberRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AddMemberRequest) GetMac() []string {
	if x != nil {
		return x.Mac
	}
	return nil
}

type AddMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{8}
}

type DeleteMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	List    []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DeleteMembersRequest) Reset() {
	*x = DeleteMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembersRequest) ProtoMessage() {}

func (x *DeleteMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembersRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMembersRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DeleteMembersRequest) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type DeleteMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMembersResponse) Reset() {
	*x = DeleteMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembersResponse) ProtoMessage() {}

func (x *DeleteMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembersResponse.ProtoReflect.Descriptor instead.
func (*DeleteMembersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{10}
}

type GetMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{11}
}

func (x *GetMembersRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{12}
}

func (x *GetMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac        string `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip4        *Lease `protobuf:"bytes,3,opt,name=ip4,proto3" json:"ip4,omitempty"`
	Ip6        *Lease `protobuf:"bytes,4,opt,name=ip6,proto3" json:"ip6,omitempty"`
	Net        string `protobuf:"bytes,5,opt,name=net,proto3" json:"net,omitempty"`
	ClientName string `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{13}
}

func (x *Member) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetIp4() *Lease {
	if x != nil {
		return x.Ip4
	}
	return nil
}

func (x *Member) GetIp6() *Lease {
	if x != nil {
		return x.Ip6
	}
	return nil
}

func (x *Member) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *Member) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type Lease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Expires *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
}

func (x *Lease) Reset() {
	*x = Lease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{14}
}

func (x *Lease) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Lease) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type MemberUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mac  string                  `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Name *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip4  *Lease                  `protobuf:"bytes,3,opt,name=ip4,proto3" json:"ip4,omitempty"`
	Ip6  *Lease                  `protobuf:"bytes,4,opt,name=ip6,proto3" json:"ip6,omitempty"`
}

func (x *MemberUpdate) Reset() {
	*x = MemberUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberUpdate) ProtoMessage() {}

func (x *MemberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberUpdate.ProtoReflect.Descriptor instead.
func (*MemberUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{15}
}

func (x *MemberUpdate) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *MemberUpdate) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MemberUpdate) GetIp4() *Lease {
	if x != nil {
		return x.Ip4
	}
	return nil
}

func (x *MemberUpdate) GetIp6() *Lease {
	if x != nil {
		return x.Ip6
	}
	return nil
}

type MemberList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Net   string    `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	List  []*Member `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Force bool      `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{16}
}

func (x *MemberList) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *MemberList) GetList() []*Member {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MemberList) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type AddMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMembersResponse) Reset() {
	*x = AddMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersResponse) ProtoMessage() {}

func (x *AddMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersResponse.ProtoReflect.Descriptor instead.
func (*AddMembersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{17}
}

type UpdateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Net  string          `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	List []*MemberUpdate `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UpdateList) Reset() {
	*x = UpdateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateList) ProtoMessage() {}

func (x *UpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateList.ProtoReflect.Descriptor instead.
func (*UpdateList) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateList) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *UpdateList) GetList() []*MemberUpdate {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMembersResponse) Reset() {
	*x = UpdateMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMembersResponse) ProtoMessage() {}

func (x *UpdateMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMembersResponse.ProtoReflect.Descriptor instead.
func (*UpdateMembersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{19}
}

type AddNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network *Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *AddNetworkRequest) Reset() {
	*x = AddNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkRequest) ProtoMessage() {}

func (x *AddNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{20}
}

func (x *AddNetworkRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type AddNetworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddNetworkResponse) Reset() {
	*x = AddNetworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkResponse) ProtoMessage() {}

func (x *AddNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{21}
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteNetworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{23}
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{24}
}

func (x *GetNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNetworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Net *Network `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{25}
}

func (x *GetNetworkResponse) GetNet() *Network {
	if x != nil {
		return x.Net
	}
	return nil
}

type GetNetworksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNetworksRequest) Reset() {
	*x = GetNetworksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksRequest) ProtoMessage() {}

func (x *GetNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksRequest.ProtoReflect.Descriptor instead.
func (*GetNetworksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{26}
}

type GetNetworksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//repeated Network nets = 1;
	Nets []string `protobuf:"bytes,1,rep,name=nets,proto3" json:"nets,omitempty"`
}

func (x *GetNetworksResponse) Reset() {
	*x = GetNetworksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksResponse) ProtoMessage() {}

func (x *GetNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksResponse.ProtoReflect.Descriptor instead.
func (*GetNetworksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{27}
}

func (x *GetNetworksResponse) GetNets() []string {
	if x != nil {
		return x.Nets
	}
	return nil
}

type ChangeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Net  string      `protobuf:"bytes,1,opt,name=net,proto3" json:"net,omitempty"`
	List []*IDChange `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ChangeList) Reset() {
	*x = ChangeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeList) ProtoMessage() {}

func (x *ChangeList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeList.ProtoReflect.Descriptor instead.
func (*ChangeList) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{28}
}

func (x *ChangeList) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *ChangeList) GetList() []*IDChange {
	if x != nil {
		return x.List
	}
	return nil
}

type IDChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old string `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New string `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *IDChange) Reset() {
	*x = IDChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDChange) ProtoMessage() {}

func (x *IDChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDChange.ProtoReflect.Descriptor instead.
func (*IDChange) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{29}
}

func (x *IDChange) GetOld() string {
	if x != nil {
		return x.Old
	}
	return ""
}

func (x *IDChange) GetNew() string {
	if x != nil {
		return x.New
	}
	return ""
}

type ChangeMemberIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeMemberIDResponse) Reset() {
	*x = ChangeMemberIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_nex_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMemberIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMemberIDResponse) ProtoMessage() {}

func (x *ChangeMemberIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_nex_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMemberIDResponse.ProtoReflect.Descriptor instead.
func (*ChangeMemberIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_nex_proto_rawDescGZIP(), []int{30}
}

var File_pkg_nex_proto protoreflect.FileDescriptor

var file_pkg_nex_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6e, 0x65, 0x78, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a,
	0x11, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xc3, 0x03, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x68, 0x63, 0x70, 0x34, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x68, 0x63,
	0x70, 0x34, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x68, 0x63, 0x70,
	0x36, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x68, 0x63, 0x70, 0x36, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x34, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x36, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x36,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x25,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xee, 0x06, 0x0a, 0x14, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x34, 0x12, 0x36, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x36, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x68, 0x63, 0x70, 0x34, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x64, 0x68, 0x63, 0x70, 0x34, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x68, 0x63, 0x70, 0x36, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x64, 0x68, 0x63, 0x70, 0x36, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x34, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x34,
	0x12, 0x29, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x36, 0x12, 0x29, 0x0a, 0x10, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x73, 0x5f, 0x61, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x73, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12,
	0x2f, 0x0a, 0x13, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x5f, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x12, 0x2d, 0x0a, 0x12, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x5f,
	0x61, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12,
	0x34, 0x0a, 0x0f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x61, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x6e, 0x65, 0x78, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x61, 0x63, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x34,
	0x0a, 0x06, 0x73, 0x69, 0x61, 0x64, 0x64, 0x72, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x73, 0x69,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x43, 0x0a, 0x0e, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55,
	0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x36, 0x0a, 0x06, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x3e, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x61, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x17, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x3b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e,
	0x65, 0x78, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x69, 0x70, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x03, 0x69, 0x70,
	0x34, 0x12, 0x1c, 0x0a, 0x03, 0x69, 0x70, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x03, 0x69, 0x70, 0x36, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x57, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0c,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x30,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x03, 0x69, 0x70, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x6e, 0x65, 0x78, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x03, 0x69, 0x70, 0x34, 0x12, 0x1c,
	0x0a, 0x03, 0x69, 0x70, 0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6e, 0x65,
	0x78, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x03, 0x69, 0x70, 0x36, 0x22, 0x55, 0x0a, 0x0a,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e, 0x65, 0x78,
	0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x41, 0x64, 0x64,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6e, 0x65, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x03, 0x6e, 0x65, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x65, 0x74,
	0x73, 0x22, 0x41, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x65,
	0x74, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x49, 0x44, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x08, 0x49, 0x44, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f,
	0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6e, 0x65, 0x77, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93,
	0x06, 0x0a, 0x03, 0x4e, 0x65, 0x78, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e,
	0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x0f, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x19,
	0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x65, 0x78, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x0f, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0f, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x12, 0x17, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x65,
	0x78, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x16, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x65,
	0x78, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x16, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x65, 0x78,
	0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x12, 0x19, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x19, 0x2e, 0x6e,
	0x65, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e, 0x65, 0x78,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x6e, 0x65, 0x78, 0x2e, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e,
	0x65, 0x78, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x74, 0x62, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x2f,
	0x6e, 0x65, 0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_nex_proto_rawDescOnce sync.Once
	file_pkg_nex_proto_rawDescData = file_pkg_nex_proto_rawDesc
)

func file_pkg_nex_proto_rawDescGZIP() []byte {
	file_pkg_nex_proto_rawDescOnce.Do(func() {
		file_pkg_nex_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_nex_proto_rawDescData)
	})
	return file_pkg_nex_proto_rawDescData
}

var file_pkg_nex_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pkg_nex_proto_goTypes = []interface{}{
	(*InterfaceRequest)(nil),       // 0: nex.InterfaceRequest
	(*InterfaceResponse)(nil),      // 1: nex.InterfaceResponse
	(*Network)(nil),                // 2: nex.Network
	(*NetworkUpdateRequest)(nil),   // 3: nex.NetworkUpdateRequest
	(*NetworkUpdateResponse)(nil),  // 4: nex.NetworkUpdateResponse
	(*AddressRange)(nil),           // 5: nex.AddressRange
	(*Option)(nil),                 // 6: nex.Option
	(*AddMemberRequest)(nil),       // 7: nex.AddMemberRequest
	(*AddMemberResponse)(nil),      // 8: nex.AddMemberResponse
	(*DeleteMembersRequest)(nil),   // 9: nex.DeleteMembersRequest
	(*DeleteMembersResponse)(nil),  // 10: nex.DeleteMembersResponse
	(*GetMembersRequest)(nil),      // 11: nex.GetMembersRequest
	(*GetMembersResponse)(nil),     // 12: nex.GetMembersResponse
	(*Member)(nil),                 // 13: nex.Member
	(*Lease)(nil),                  // 14: nex.Lease
	(*MemberUpdate)(nil),           // 15: nex.MemberUpdate
	(*MemberList)(nil),             // 16: nex.MemberList
	(*AddMembersResponse)(nil),     // 17: nex.AddMembersResponse
	(*UpdateList)(nil),             // 18: nex.UpdateList
	(*UpdateMembersResponse)(nil),  // 19: nex.UpdateMembersResponse
	(*AddNetworkRequest)(nil),      // 20: nex.AddNetworkRequest
	(*AddNetworkResponse)(nil),     // 21: nex.AddNetworkResponse
	(*DeleteNetworkRequest)(nil),   // 22: nex.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil),  // 23: nex.DeleteNetworkResponse
	(*GetNetworkRequest)(nil),      // 24: nex.GetNetworkRequest
	(*GetNetworkResponse)(nil),     // 25: nex.GetNetworkResponse
	(*GetNetworksRequest)(nil),     // 26: nex.GetNetworksRequest
	(*GetNetworksResponse)(nil),    // 27: nex.GetNetworksResponse
	(*ChangeList)(nil),             // 28: nex.ChangeList
	(*IDChange)(nil),               // 29: nex.IDChange
	(*ChangeMemberIDResponse)(nil), // 30: nex.ChangeMemberIDResponse
	(*wrapperspb.StringValue)(nil), // 31: google.protobuf.StringValue
	(*wrapperspb.UInt64Value)(nil), // 32: google.protobuf.UInt64Value
	(*timestamppb.Timestamp)(nil),  // 33: google.protobuf.Timestamp
}
var file_pkg_nex_proto_depIdxs = []int32{
	5,  // 0: nex.Network.range4:type_name -> nex.AddressRange
	5,  // 1: nex.Network.range6:type_name -> nex.AddressRange
	6,  // 2: nex.Network.options:type_name -> nex.Option
	31, // 3: nex.NetworkUpdateRequest.subnet4:type_name -> google.protobuf.StringValue
	31, // 4: nex.NetworkUpdateRequest.subnet6:type_name -> google.protobuf.StringValue
	31, // 5: nex.NetworkUpdateRequest.dhcp4server:type_name -> google.protobuf.StringValue
	31, // 6: nex.NetworkUpdateRequest.dhcp6server:type_name -> google.protobuf.StringValue
	5,  // 7: nex.NetworkUpdateRequest.Range4:type_name -> nex.AddressRange
	5,  // 8: nex.NetworkUpdateRequest.Range6:type_name -> nex.AddressRange
	6,  // 9: nex.NetworkUpdateRequest.options_present:type_name -> nex.Option
	6,  // 10: nex.NetworkUpdateRequest.options_absent:type_name -> nex.Option
	31, // 11: nex.NetworkUpdateRequest.domain:type_name -> google.protobuf.StringValue
	5,  // 12: nex.NetworkUpdateRequest.macRange:type_name -> nex.AddressRange
	31, // 13: nex.NetworkUpdateRequest.siaddr:type_name -> google.protobuf.StringValue
	32, // 14: nex.NetworkUpdateRequest.lease_duration:type_name -> google.protobuf.UInt64Value
	13, // 15: nex.GetMembersResponse.members:type_name -> nex.Member
	14, // 16: nex.Member.ip4:type_name -> nex.Lease
	14, // 17: nex.Member.ip6:type_name -> nex.Lease
	33, // 18: nex.Lease.expires:type_name -> google.protobuf.Timestamp
	31, // 19: nex.MemberUpdate.name:type_name -> google.protobuf.StringValue
	14, // 20: nex.MemberUpdate.ip4:type_name -> nex.Lease
	14, // 21: nex.MemberUpdate.ip6:type_name -> nex.Lease
	13, // 22: nex.MemberList.list:type_name -> nex.Member
	15, // 23: nex.UpdateList.list:type_name -> nex.MemberUpdate
	2,  // 24: nex.AddNetworkRequest.network:type_name -> nex.Network
	2,  // 25: nex.GetNetworkResponse.net:type_name -> nex.Network
	29, // 26: nex.ChangeList.list:type_name -> nex.IDChange
	11, // 27: nex.Nex.GetMembers:input_type -> nex.GetMembersRequest
	16, // 28: nex.Nex.AddMembers:input_type -> nex.MemberList
	9,  // 29: nex.Nex.DeleteMembers:input_type -> nex.DeleteMembersRequest
	18, // 30: nex.Nex.UpdateMembers:input_type -> nex.UpdateList
	28, // 31: nex.Nex.ChangeMemberID:input_type -> nex.ChangeList
	26, // 32: nex.Nex.GetNetworks:input_type -> nex.GetNetworksRequest
	24, // 33: nex.Nex.GetNetwork:input_type -> nex.GetNetworkRequest
	20, // 34: nex.Nex.AddNetwork:input_type -> nex.AddNetworkRequest
	3,  // 35: nex.Nex.UpdateNetwork:input_type -> nex.NetworkUpdateRequest
	22, // 36: nex.Nex.DeleteNetwork:input_type -> nex.DeleteNetworkRequest
	0,  // 37: nex.Nex.AddInterface:input_type -> nex.InterfaceRequest
	0,  // 38: nex.Nex.DeleteInterface:input_type -> nex.InterfaceRequest
	12, // 39: nex.Nex.GetMembers:output_type -> nex.GetMembersResponse
	17, // 40: nex.Nex.AddMembers:output_type -> nex.AddMembersResponse
	10, // 41: nex.Nex.DeleteMembers:output_type -> nex.DeleteMembersResponse
	19, // 42: nex.Nex.UpdateMembers:output_type -> nex.UpdateMembersResponse
	30, // 43: nex.Nex.ChangeMemberID:output_type -> nex.ChangeMemberIDResponse
	27, // 44: nex.Nex.GetNetworks:output_type -> nex.GetNetworksResponse
	25, // 45: nex.Nex.GetNetwork:output_type -> nex.GetNetworkResponse
	21, // 46: nex.Nex.AddNetwork:output_type -> nex.AddNetworkResponse
	4,  // 47: nex.Nex.UpdateNetwork:output_type -> nex.NetworkUpdateResponse
	23, // 48: nex.Nex.DeleteNetwork:output_type -> nex.DeleteNetworkResponse
	1,  // 49: nex.Nex.AddInterface:output_type -> nex.InterfaceResponse
	1,  // 50: nex.Nex.DeleteInterface:output_type -> nex.InterfaceResponse
	39, // [39:51] is the sub-list for method output_type
	27, // [27:39] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_pkg_nex_proto_init() }
func file_pkg_nex_proto_init() {
	if File_pkg_nex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_nex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNetworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNetworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNetworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNetworksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNetworksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_nex_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMemberIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_nex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_nex_proto_goTypes,
		DependencyIndexes: file_pkg_nex_proto_depIdxs,
		MessageInfos:      file_pkg_nex_proto_msgTypes,
	}.Build()
	File_pkg_nex_proto = out.File
	file_pkg_nex_proto_rawDesc = nil
	file_pkg_nex_proto_goTypes = nil
	file_pkg_nex_proto_depIdxs = nil
}
